### ISSUE TITLE
8th Edition - Catalogue Progress Tracker

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-heralds-of-ruin-killteam#130]
### Existing Opuses
 - [x] Adepta Sororitas
 - [ ] Adeptus Arbites
 - [ ] Astra Militarum
 - [ ] Black Templars
 - [ ] Blood Angels
 - [ ] Chaos Daemons
 - [ ] Chaos Space Marines
 - [ ] Craftworld Eldar
 - [ ] Dark Eldar
 - [x] Death Guard
 - [ ] Deathwatch
 - [ ] Eldar
 - [ ] Genestealer Cults
 - [ ] Grey Knights
 - [ ] Inquisition
 - [ ] Orks
 - [ ] Primaris Space Marines
 - [ ] Rak'Gol
 - [x] Renegades & Heretics*
 - [ ] Rogue Traders
 - [ ] Space Marines
 - [ ] Space Wolves
 - [ ] Tau Empire
 - [ ] Talons of The Emperor
 - [ ] Thunder Warriors
 - [ ] Tyranids
 - [ ] Vyrmunn (Skaven)
 
##### * Renegades & Heretics from an unreleased opus.

 ---

### Historical Factions (No Opus)
 - Adeptus Mechanicus
 - Eldar Corsairs
 - Eldar Exodites
 - Eldar Harlequins
 - Feral Orks
 - Gaunt's Ghosts (Tanith First and Only)
 - Grot Rebels
 - Hrud
 - Imperial/Cult Militia
 - Khorne Deamonkin
 - Kroot Mercenaries
 - Last Chancers
 - Legiones Astartes - Loyalist Legions
 - Legiones Astartes - Traitor Legions
 - Mechanicum
 - Necrons
 - Officio Assassinorum
 - Ogryns
 - Solar Auxilia
 - Sons of Malice Chaos Warbands
 - Squats
